import { useState } from "react";
import { useNavigate } from "react-router-dom";

import FormErrorSummary from "../../../components/feedback/FormErrorSummary.jsx";
import SEO from "../../../components/seo/SEO.jsx";
import { createContact } from "../api/crm.service.js";
import { crmPriorities, crmStatuses } from "../config/crm.config.js";

export default function AdminContactEditorPage() {
  const navigate = useNavigate(); const [form, setForm] = useState({ firstName: "", lastName: "", email: "", phone: "", source: "MANUAL", sourceDetail: "", status: "NOUVEAU", priority: "NORMAL", tagIds: [], marketingConsent: { granted: false, occurredAt: null, source: null } }); const [error, setError] = useState(null);
  async function submit(event) { event.preventDefault(); try { const payload = { ...form, lastName: form.lastName || null, phone: form.phone || null, sourceDetail: form.sourceDetail || null, marketingConsent: form.marketingConsent.granted ? { ...form.marketingConsent, occurredAt: new Date(form.marketingConsent.occurredAt).toISOString() } : { granted: false } }; const contact = await createContact(payload); navigate(`/administration/crm/contacts/${contact._id}`); } catch (apiError) { setError(apiError); } }
  return <main className="admin-dashboard"><SEO title="Nouveau contact" noIndex /><header><div><p className="section-eyebrow">CRM</p><h1>Ajouter un contact</h1></div></header>{error && <FormErrorSummary error={error} />}<form className="admin-form" onSubmit={submit}><section><h2>Identité et coordonnées</h2><label><span>Prénom</span><input minLength="2" maxLength="80" value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} required /></label><label><span>Nom facultatif</span><input maxLength="80" value={form.lastName} onChange={(event) => setForm({ ...form, lastName: event.target.value })} /></label><label><span>Email</span><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label><span>Téléphone facultatif</span><input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label></section><section><h2>Suivi</h2><label><span>Statut</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}>{Object.entries(crmStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Priorité</span><select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}>{Object.entries(crmPriorities).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></section><fieldset><legend>Consentement marketing</legend><label className="admin-check"><input type="checkbox" checked={form.marketingConsent.granted} onChange={(event) => setForm({ ...form, marketingConsent: { ...form.marketingConsent, granted: event.target.checked } })} /><span>Le consentement a été obtenu</span></label>{form.marketingConsent.granted && <><label><span>Date du consentement</span><input type="datetime-local" value={form.marketingConsent.occurredAt || ""} onChange={(event) => setForm({ ...form, marketingConsent: { ...form.marketingConsent, occurredAt: event.target.value } })} required /></label><label><span>Origine ou preuve</span><input value={form.marketingConsent.source || ""} onChange={(event) => setForm({ ...form, marketingConsent: { ...form.marketingConsent, source: event.target.value } })} required /></label></>}</fieldset><button className="btn btn-primary">Créer le contact</button></form></main>;
}
