import { useState } from "react";

import FormErrorSummary from "../../../components/feedback/FormErrorSummary.jsx";
import SEO from "../../../components/seo/SEO.jsx";
import { runCrossAnalysis } from "../api/dashboard.service.js";

const criteria = { SPM_PROFILE: "Profil SPM", CONTRACEPTION: "Contraception", AGE_RANGE: "Tranche d’âge", QUIZ_CATEGORY: "Catégorie du quiz", CONTACT_KIND: "Type de contact", WEBINAR_PARTICIPATION: "Participation aux webinaires" };
export default function AdminAnalysesPage() {
  const [form, setForm] = useState({ primaryCriterion: "SPM_PROFILE", secondaryCriterion: "AGE_RANGE", includeAnonymized: false }); const [data, setData] = useState(null); const [error, setError] = useState(null);
  async function submit(event) { event.preventDefault(); try { setData(await runCrossAnalysis({ ...form, filters: {}, groups: [] })); } catch (apiError) { setError(apiError); } }
  return <main className="admin-dashboard"><SEO title="Analyses croisées" noIndex /><header><div><p className="section-eyebrow">Mieux comprendre</p><h1>Analyses croisées</h1><p>Les résultats utilisent uniquement le dernier quiz de chaque personne.</p></div></header>{error && <FormErrorSummary error={error} />}<form className="admin-analysis-form" onSubmit={submit}><label><span>Critère principal</span><select value={form.primaryCriterion} onChange={(event) => setForm({ ...form, primaryCriterion: event.target.value })}>{Object.entries(criteria).map(([value, label]) => <option key={value} value={value} disabled={value === form.secondaryCriterion}>{label}</option>)}</select></label><label><span>Critère secondaire</span><select value={form.secondaryCriterion} onChange={(event) => setForm({ ...form, secondaryCriterion: event.target.value })}>{Object.entries(criteria).map(([value, label]) => <option key={value} value={value} disabled={value === form.primaryCriterion}>{label}</option>)}</select></label><label className="admin-check"><input type="checkbox" checked={form.includeAnonymized} onChange={(event) => setForm({ ...form, includeAnonymized: event.target.checked })} /><span>Inclure les données anonymisées compatibles</span></label><button className="btn btn-primary">Lancer l’analyse</button></form>{data && <section><h2>Résultats · {data.population} personnes</h2><div className="admin-data-list">{data.results.map((row) => <article key={`${row.primary}-${row.secondary}`}><strong>{row.primary} × {row.secondary}</strong><span>{row.count} personne{row.count > 1 ? "s" : ""}</span><span>{row.insufficientSample ? "Échantillon insuffisant pour présenter un pourcentage fiable." : `${row.percentage} %`}</span></article>)}</div></section>}</main>;
}
