import { Link } from "react-router-dom";

import SEO from "../components/seo/SEO.jsx";
import { routes } from "../config/routes.config.js";
import { accompanimentOffers, accompanimentsContent } from "../content/accompaniments.content.js";

import "../styles/pages/editorial-premium.scss";

export default function AccompanimentDetailPage({ offerId }) {
  const offer = accompanimentOffers[offerId];
  return <main id="main-content" className={`editorial-page editorial-page--offer editorial-page--${offerId}`}><SEO title={`${offer.eyebrow} — Accompagnement avec Mélanie`} description={offer.summary} url={`/accompagnements/${offer.slug}`} /><section className="editorial-hero"><div className="page-container editorial-copy"><p className="eyebrow">{offer.eyebrow}</p><h1>{offer.title}</h1><p>{offer.summary}</p><dl className="offer-facts"><div><dt>Durée</dt><dd>{offer.duration}</dd></div><div><dt>Tarif</dt><dd>{offer.price}</dd></div></dl><Link className="btn btn-primary" to={`${routes.contact}?intention=accompagnement&offre=${offer.slug}`}>Parler de mon besoin</Link></div></section><section className="editorial-section"><div className="page-container editorial-detail-grid"><div><p className="eyebrow">Pour qui ?</p><h2>Cet accompagnement peut te correspondre si…</h2><ul className="editorial-checks">{offer.forWho.map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="eyebrow">Ce que nous explorons</p><h2>Un espace construit autour de ton vécu.</h2><ul className="editorial-checks">{offer.exploration.map((item) => <li key={item}>{item}</li>)}</ul></div></div></section><section className="editorial-section editorial-section--warm"><div className="page-container editorial-copy"><p className="eyebrow">Déroulement</p><h2>Avancer étape après étape.</h2><ol className="editorial-steps">{offer.process.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></li>)}</ol></div></section>{offer.pricing && <section className="editorial-section"><div className="page-container"><header className="section-header"><p className="eyebrow">Tarifs 2026</p><h2>Choisir selon ton objectif.</h2></header><div className="pricing-grid">{offer.pricing.map((item) => <article key={item.name}><h3>{item.name}</h3><p>{item.detail}</p><strong>{item.price}</strong></article>)}</div><p className="pricing-note">{offer.note}</p></div></section>}<section className="editorial-section editorial-section--accent"><div className="page-container editorial-copy"><h2>Un cadre clair avant de commencer.</h2><p>{accompanimentsContent.note}</p><div className="editorial-actions"><Link className="btn btn-primary" to={`${routes.contact}?intention=accompagnement&offre=${offer.slug}`}>Échanger avec Mélanie</Link><Link className="btn btn-secondary" to={routes.accompaniments}>Comparer les accompagnements</Link></div></div></section></main>;
}
